kind: pipeline
type: docker
name: Test

steps:

  - name: create_postgres_db
    image: postgres:9-alpine
    commands:
      - sleep 30
      - psql -h postgres -U postgres -c "CREATE DATABASE crisp_dev;"

  - name: Create Crisp Config
    image: alpine
    commands:
      - cd cms
      - echo -e "POSTGRES_URI=postgres://postgres:postgres@postgres:5432/crisp_dev" > .env
      - echo -e "REDIS_HOST=redis" >> .env
      - echo -e "REDIS_PORT=6379" >> .env
      - echo -e "REDIS_INDEX=2" >> .env
      - echo -e "DEFAULT_LOCALE=de" >> .env
      - echo -e "CRISP_FLAGSMITH_API_KEY=4EfrHdnZR3immHjchjUB8p" >> .env
      - echo -e "CRISP_THEME=crisptheme" >> .env
      - echo -e "LANG=de_DE.utf8" >> .env
      - echo -e "DEFAULT_LOCALE=de" >> .env


  - name: Migrate and Test Crisp
    image: php:8.1-buster
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      ENVIRONMENT: development
      GIT_COMMIT: ${DRONE_COMMIT_SHA:0:8}
      SENTRY_URL: https://sentry.internal.jrbit.de
      SENTRY_AUTH_TOKEN:
        from_secret: sentry_token
      SENTRY_ORG: jrbit
    commands:
      - mkdir /tmp/ci
      - cd /tmp/ci
      - apt-get update && apt-get install -y libpq-dev autoconf gcc libc6-dev make libicu-dev wget git-core zip zlib1g-dev libpng-dev doxygen
      - pecl install redis
      - docker-php-ext-install pgsql pdo_pgsql pdo_mysql intl gd gettext
      - docker-php-ext-enable pdo_pgsql pdo_mysql redis intl gd gettext
      - wget https://getcomposer.org/composer-stable.phar -O /tmp/ci/composer
      - cd /drone/src/cms
      - php /tmp/ci/composer install
      - php bin/cli.php migrate
      - php bin/cli.php theme install basic
      - rm /tmp/ci/composer
      #- curl -sL https://sentry.io/get-cli/ | bash
      - export VERSION=$(php bin/cli.php release)
      #- sentry-cli releases new --finalize -p crisp-core $VERSION
      #- sentry-cli releases set-commits --auto $VERSION


services:
  - name: redis
    image: redis
  - name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

---
kind: pipeline
type: docker
name: Build Docker Images

steps:

  - name: en_US.amd64
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      auto_tag: true
      password:
        from_secret: docker_secret
      repo: docker.io/jrbit/crispcms
      registry: docker.io
      squash: true
      build_args:
        - GIT_COMMIT=${DRONE_COMMIT_SHA:0:8}
        - LANG=en_US.UTF-8
        - DEFAULT_LOCALE=en
    when:
      ref:
        - refs/heads/master
        - refs/tags/*
      event:
        include:
          - tag
          - push
    depends_on: [ clone ]
depends_on:
  - Test
