
#image:
#  file: .gitpod.Dockerfile

ports:
  - name: Frontend
    description: CrispCMS Frontend
    port: 80
    onOpen: notify

  - name: API
    description: CrispCMS API Server
    port: 81
    onOpen: notify

  - name: Postgresql
    description: RDBMS Server
    port: 5432
    onOpen: ignore

  - name: Mailhog SMTP
    description: Dev SMTP server
    port: 1025
    onOpen: ignore

  - name: Mailhog Web
    description: Dev Mailhog Web server
    port: 8025
    onOpen: notify

  - name: Adminer
    description: Database Manager
    port: 8080
    onOpen: notify

tasks:

  - command: gp preview $(gp url 80)/_debug

  - name: Docsify
    command: 'npm i docsify-cli -g && docsify serve ./docs'

  - name: CrispCMS
    init: docker build -t crispcms . && git clone https://gitlab.jrbit.de/crispcms/theme-template theme && mv theme/theme cms/themes/crisptheme && rm -rf theme
    command: npm install --global prettier @prettier/plugin-php && ./startup_dev.sh

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - TeamHub.teamhub
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
    - mblode.twig-language-2
    - GitLab.gitlab-workflow
    - DEVSENSE.composer-php-vscode
    - caponetto.vscode-diff-viewer
    - 42Crunch.vscode-openapi
    - mjmlio.vscode-mjml
    - junstyle.php-cs-fixer
    - esbenp.prettier-vscode
