
image:
  file: .gitpod.Dockerfile

ports:
  - name: Frontend
    description: CrispCMS Frontend
    port: 80
    onOpen: notify

  - name: API
    description: CrispCMS API Server
    port: 81
    onOpen: notify

  - name: Postgresql
    description: RDBMS Server
    port: 5432
    onOpen: ignore

  - name: Redis
    description: Session and Ratelimit Server
    port: 6379
    onOpen: ignore

  - name: FPM
    description: PHP FPM server
    port: 9000
    onOpen: ignore

  - name: Mailhog SMTP
    description: Dev SMTP server
    port: 1025
    onOpen: ignore

  - name: Mailhog Web
    description: Dev Mailhog Web server
    port: 8025
    onOpen: notify

  - name: pgAdmin
    description: Database Manager
    port: 5050
    onOpen: notify
tasks:
  - name: Postgres
    init: docker pull postgres
    command: 'docker run -p 5432:5432 --name postgres -e POSTGRES_PASSWORD=postgres --net="host" --rm postgres'

  - name: Redis
    init: docker pull redis
    command: 'docker run -p 6379:6379 --name redis --net="host" --rm redis'


  - name: Mailhog
    init: docker pull mailhog/mailhog
    command: 'docker run -p 1025:1025 -p 8025:8025 --name mailhog --net="host" --rm mailhog/mailhog'

  - name: CrispCMS
    init: cd cms && composer install
    env:
      CRISP_WORKDIR: "${GITPOD_REPO_ROOT}/cms"
    command: gp ports await 5432 && gp ports await 6379 && 
             crisp-cli migrate && 
             crisp-cli theme install "$CRISP_THEME" &&
             crisp-cli theme reload "$CRISP_THEME" overwrite &&
             crisp-cli theme migrate "$CRISP_THEME" &&
             crisp-cli cache clear &&
             crisp-cli theme boot "$CRISP_THEME" &&

  - name: PHP
    command: php-fpm -F -R -D

  - name: Nginx
    command: nginx -c ${GITPOD_REPO_ROOT}/config/nginx.conf -g "daemon off;"

  - name: pgAdmin
  - init: docker pull dpage/pgadmin4
  - command: docker run --name pgadmin --rm --net="host" -p 5050:80 -e PGADMIN_DEFAULT_EMAIL=pgadmin@crispcms.de -e PGADMIN_DEFAULT_PASSWORD=password -e PGADMIN_CONFIG_SERVER_MODE=False dpage/pgadmin4 

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - TeamHub.teamhub
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
    - mblode.twig-language-2
    - GitLab.gitlab-workflow
    - DEVSENSE.composer-php-vscode
    - caponetto.vscode-diff-viewer
    - 42Crunch.vscode-openapi
    - mjmlio.vscode-mjml
