
#image:
#  file: .gitpod.Dockerfile

ports:
  - name: Frontend
    description: CrispCMS Frontend
    port: 80
    onOpen: notify

  - name: API
    description: CrispCMS API Server
    port: 81
    onOpen: notify

  - name: Postgresql
    description: RDBMS Server
    port: 5432
    onOpen: ignore

  - name: Redis
    description: Session and Ratelimit Server
    port: 6379
    onOpen: ignore

  - name: Mailhog SMTP
    description: Dev SMTP server
    port: 1025
    onOpen: ignore

  - name: Mailhog Web
    description: Dev Mailhog Web server
    port: 8025
    onOpen: notify

  - name: Adminer
    description: Database Manager
    port: 8080
    onOpen: notify
tasks:

  - command: gp preview $(gp url 80)/_debug

  - name: Postgres
    init: docker pull postgres
    command: 'docker run -p 5432:5432 --name postgres -e POSTGRES_PASSWORD=postgres --net="host" --rm postgres'

  - name: Redis
    init: docker pull redis
    command: 'docker run -p 6379:6379 --name redis --net="host" --rm redis'


  - name: Mailhog
    init: docker pull mailhog/mailhog
    command: 'docker run -p 1025:1025 -p 8025:8025 --name mailhog --net="host" --rm mailhog/mailhog'

  - name: Docsify
    command: 'npm i docsify-cli -g && docsify serve ./docs'

  - name: CrispCMS
    init: docker build -t crispcms . && git clone https://gitlab.jrbit.de/crispcms/theme-template theme && mv theme/theme cms/themes/crisptheme && rm -rf theme
    command: gp ports await 5432 && gp ports await 6379 && docker run --name crispcms
      -e CRISP_THEME=crisptheme
      -e VERBOSITY=3
      -e POSTGRES_URI=postgres://postgres:postgres@localhost:5432/postgres
      -e REDIS_HOST=localhost
      -e TZ=Europe/Berlin
      -e REDIS_INDEX=1
      -e HOST=$(gp url 80 | sed -E 's_^https?://__')
      -e ROOT=$(gp url 80 | sed -E 's_^https?://__')
      -e PROTO=https
      -e SENTRY_DSN=https://e1335d78665742d0bbd9a67935dbc6ed@sentry.internal.jrbit.de/5
      -e ENVIRONMENT=development
      -e CRISP_FLAGSMITH_API_KEY=K8BJRBi6xiE3HweHoRQhQA
      -e SENTRY_JS_DSN=https://sentry.internal.jrbit.de/js-sdk-loader/e1335d78665742d0bbd9a67935dbc6ed.min.js
      -v ${GITPOD_REPO_ROOT}/cms:/var/www/crisp
      -v ${GITPOD_REPO_ROOT}/data:/data
      -v ${GITPOD_REPO_ROOT}/config/nginx.conf:/etc/nginx/conf.d/default.conf
      --net="host"
      --rm
      crispcms

  - name: adminer
    init: docker pull adminer
    command: docker run -p 8080:8080 --name adminer --net="host" --rm adminer

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - TeamHub.teamhub
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
    - mblode.twig-language-2
    - GitLab.gitlab-workflow
    - DEVSENSE.composer-php-vscode
    - caponetto.vscode-diff-viewer
    - 42Crunch.vscode-openapi
    - mjmlio.vscode-mjml
