version: '3'
services:
  crispcms:
    build:
     context: .
    container_name: crispcms
    environment:
      - LOG_LEVEL=DEBUG
      - POSTGRES_URI=postgres://postgres:postgres@localhost:5432/postgres #gitleaks:allow
      - TZ=Europe/Berlin
      - HOST=${HOST}
      - ROOT=${HOST}
      - PROTO=https
      - SENTRY_DSN=https://4129710f0e07a134fc7291ec974cf504@o3.ingest.sentry.jrbit.de/41
      - SENTRY_SAMPLE_RATE=1.0
      - SENTRY_PROFILES_SAMPLE_RATE=1.0
      - ENVIRONMENT=development
      - SENTRY_JS_DSN=https://sentry.internal.jrbit.de/js-sdk-loader/4129710f0e07a134fc7291ec974cf504.min.js
      - GIT_TAG=${GIT_TAG}
    volumes:
      - ${GITPOD_REPO_ROOT}:/var/www/crisp
      - ${GITPOD_REPO_ROOT}/data:/data
      - ${GITPOD_REPO_ROOT}/theme/theme:/var/www/crisp/cms/themes/crisptheme
      - ${GITPOD_REPO_ROOT}/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${GITPOD_REPO_ROOT}/config/crisp-cli.sh:/usr/local/bin/crisp-cli
    user: root
    network_mode: host
    restart: always


  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres #gitleaks:allow
    ports:
      - "5432:5432"
    network_mode: host
    restart: always
    
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    network_mode: host
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    network_mode: host
    restart: always