services:

  crispcms:
    build:
     context: .
    container_name: crispcms
    links:
      - mailhog
      - postgres
    ports:
      - 80:80
      - 81:81
    environment:
      - LOG_LEVEL=DEBUG
      - POSTGRES_URI=postgres://postgres:postgres@postgres:5432/postgres #gitleaks:allow
      - TZ=Europe/Berlin
      - HOST=${HOST}
      - ROOT=${HOST}
      - PROTO=https
      - ENVIRONMENT=development
      - GIT_TAG=${GIT_TAG}
      - LICENSE_SERVER=https://castiels.prod.bl-netzwerke.de/validate/v1?key={{key}}&instance={{instance}}
      - REQUIRE_LICENSE=true
      - LICENSE_KEY=ccfe847e-eb43-23c9-c535-bde03ef64cf0 #gitleaks:allow Development License Key
    volumes:
      - ${GITPOD_REPO_ROOT}:/var/www/crisp
      - crisp:/data
      - ${GITPOD_REPO_ROOT}/theme/public:/var/www/crisp/cms/themes/crisptheme
      - ${GITPOD_REPO_ROOT}/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${GITPOD_REPO_ROOT}/config/crisp-cli.sh:/usr/local/bin/crisp-cli
      - ${GITPOD_REPO_ROOT}/docker:/opt/entrypoint.d
    user: root


  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres #gitleaks:allow
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

  adminer:
    image: adminer
    links:
      - postgres
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres:
  crisp: