services:
  postgres_license:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres #gitleaks:allow


  license:
    image: registry.jrbit.de/jrb-it/rest-license:stable
    links:
      - postgres_license
    environment:
      - LOG_LEVEL=DEBUG
      - POSTGRES_URI=postgres://postgres:postgres@postgres_license:5432/postgres #gitleaks:allow
      - TZ=Europe/Berlin
      - HOST=${HOST}
      - ROOT=${HOST}
      - PROTO=https
      - SENTRY_DSN=https://4129710f0e07a134fc7291ec974cf504@o3.ingest.sentry.jrbit.de/41
      - SENTRY_SAMPLE_RATE=1.0
      - SENTRY_PROFILES_SAMPLE_RATE=1.0
      - ENVIRONMENT=production
      - REST_MASTER_KEY=dev
      - SENTRY_JS_DSN=https://sentry.internal.jrbit.de/js-sdk-loader/4129710f0e07a134fc7291ec974cf504.min.js


  crispcms:
    build:
     context: .
    container_name: crispcms
    links:
      - license
      - mailhog
      - postgres
    ports:
      - 80:80
      - 81:81
    environment:
      - LOG_LEVEL=DEBUG
      - POSTGRES_URI=postgres://postgres:postgres@postgres:5432/postgres #gitleaks:allow
      - TZ=Europe/Berlin
      - HOST=${HOST}
      - ROOT=${HOST}
      - PROTO=https
      - ENVIRONMENT=development
      - GIT_TAG=${GIT_TAG}
      - LICENSE_SERVER=http://license:81/validate/v1?key={{key}}&instance={{instance}}
      - REQUIRE_LICENSE=true
      #- LICENSE_KEY=testKey
    volumes:
      - ${GITPOD_REPO_ROOT}:/var/www/crisp
      - crisp:/data
      - ${GITPOD_REPO_ROOT}/theme/public:/var/www/crisp/cms/themes/crisptheme
      - ${GITPOD_REPO_ROOT}/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${GITPOD_REPO_ROOT}/config/crisp-cli.sh:/usr/local/bin/crisp-cli
      - ${GITPOD_REPO_ROOT}/docker:/opt/entrypoint.d
    user: root


  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres #gitleaks:allow
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

  adminer:
    image: adminer
    links:
      - postgres
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres:
  crisp: