#!/bin/bash


cd "$CRISP_WORKDIR" || exit 1


if [ -z "$SKIP_COMPOSER" ]; then
  /usr/local/bin/composer install
fi

if [ ! -f .env ]
then
  echo "# Additional environment variables below" > .env || exit 1
fi

if [[ -z "${ASSETS_S3_BUCKET}" ]]; then
  echo "Not deploying to S3"
else
  crisp-cli assets --deploy-to-s3
fi

sed -i -e "s/# $LANG UTF-8/$LANG UTF-8/" /etc/locale.gen
dpkg-reconfigure --frontend=noninteractive locales
update-locale LANG="$LANG"

if [[ -z "${MAXMIND_LICENSE}" || -z "${MAXMIND_ACCOUNT_ID}" || -z "${MAXMIND_EDITION_IDS}" ]]; then
  echo "No Maxmind credentials found, not updating geoip"
else
  echo -e "# Generated By CrispCMS" > /etc/GeoIP.conf
  echo -e "AccountID $MAXMIND_ACCOUNT_ID\n" >> /etc/GeoIP.conf
  echo -e "LicenseKey $MAXMIND_LICENSE\n" >> /etc/GeoIP.conf
  echo -e "EditionIDs $MAXMIND_EDITION_IDS\n" >> /etc/GeoIP.conf
  geoipupdate
fi


cd / || exit 1

export BOOTSTRAPPED=true
