version: '3.3'
services:

  crisp:
    image: 'jrbit/crispcms-ce:latest'
    volumes:
      - ../cms:/var/www/crisp
      - ../config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../config/php.ini:/usr/local/etc/php/conf.d/php_custom.ini
      - ./data/crisp/theme/theme:/var/www/crisp/themes/crisptheme
    ports:
      - '80:80'
    links:
      - postgres
      - redis
    environment:
      - CRISP_THEME=crisptheme
      - VERBOSITY=3
      - POSTGRES_URI=postgres://postgres:postgres@postgres:5432/postgres
      - REDIS_HOST=redis
      - REDIS_INDEX=1
      #- SENTRY_DSN=https://e2ebf539e09b4e8cada7aa2145034028@sentry.jrbit.de/10
      - ENVIRONMENT=development
      - FLAGSMITH_API_KEY=KoHrHtcqdTCeSjsjXjzCSL
      - FLAGSMITH_APP_URL=https://flagsmith.internal.jrbit.de/api/v1/
      - CRISP_FLAGSMITH_API_KEY=K8BJRBi6xiE3HweHoRQhQA
      #- SENTRY_JS_DSN=https://sentry.jrbit.de/js-sdk-loader/2053162a36cb49aea4223b35051e9493.min.js

  redis:
    image: redis:latest
    restart: always

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
