#!/bin/bash

if [ -z "$BOOTSTRAPPED" ]; then
  source /opt/entrypoint.d/bootstrap.sh
fi


if [ -z "$CRISP_THEME" ]; then
  echo "Missing Environment Variable CRISP_THEME"
  exit 1
fi

if [ -z "$POSTGRES_URI" ]; then
  echo "Missing Environment Variable POSTGRES_URI"
  exit 1
fi

if [ -z "$REDIS_HOST" ]; then
  echo "Missing Environment Variable REDIS_HOST"
  exit 1
fi

if [ -z "$REDIS_PORT" ]; then
  echo "Missing Environment Variable REDIS_PORT"
  exit 1
fi

if [ -z "$REDIS_INDEX" ]; then
  echo "Missing Environment Variable REDIS_INDEX"
  exit 1
fi


if [ -z "$DEFAULT_LOCALE" ]; then
  echo "Missing Environment Variable DEFAULT_LOCALE"
  exit 1
fi


cd "$CRISP_WORKDIR" || exit 1

crisp-cli crisp --migrate || (echo "Failed to Migrate" && exit 1)
sleep 2
crisp-cli theme --uninstall
sleep 2
crisp-cli theme --install || (echo "Failed to install theme" && exit 1)
sleep 2
crisp-cli theme --migrate || (echo "Failed to migrate theme" && exit 1)
sleep 2
crisp-cli theme --clear-cache || (echo "Failed to clear cache" && exit 1)
sleep 2
crisp-cli theme --boot || (echo "Failed to execute boot files" && exit 1)
sleep 2
if [[ -z "${ASSETS_S3_BUCKET}" ]]; then
  echo "Not deploying to S3"
else
  crisp-cli assets --deploy-to-s3
fi


sed -i -e "s/# $LANG UTF-8/$LANG UTF-8/" /etc/locale.gen
dpkg-reconfigure --frontend=noninteractive locales
update-locale LANG="$LANG"

if [[ -z "${MAXMIND_LICENSE}" || -z "${MAXMIND_ACCOUNT_ID}" || -z "${MAXMIND_EDITION_IDS}" ]]; then
  echo "No Maxmind credentials found, not updating geoip"
else
  echo "Updating GeoIP Database..."
  echo -e "# Generated By CrispCMS" > /etc/GeoIP.conf
  echo -e "AccountID $MAXMIND_ACCOUNT_ID\n" >> /etc/GeoIP.conf
  echo -e "LicenseKey $MAXMIND_LICENSE\n" >> /etc/GeoIP.conf
  echo -e "EditionIDs $MAXMIND_EDITION_IDS\n" >> /etc/GeoIP.conf
  geoipupdate
fi

echo "Setting System Timezone..."
ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
echo "Setting PHP Timezone..."
printf "[Date]\ndate.timezone = \"$TZ\"\n" > /usr/local/etc/php/conf.d/timezone.ini

rm /tmp/* -R

cd / || exit 1

php-fpm -F -R -D || exit 1
crisp-cli crisp -p
nginx -c /etc/nginx/nginx.conf -g "daemon off;"
