#!/bin/bash

if [ -z "$BOOTSTRAPPED" ]; then
  source /opt/entrypoint.d/bootstrap.sh
fi

if [ -z "$POSTGRES_URI" ]; then
  echo "Missing Environment Variable POSTGRES_URI"
  exit 1
fi

if [ -z "$DEFAULT_LOCALE" ]; then
  echo "Missing Environment Variable DEFAULT_LOCALE"
  exit 1
fi

sudo rm -Rf /tmp/crisp-cache
mkdir /tmp/crisp-cache
sudo chown www-data:www-data -R /tmp/crisp-cache

sudo sed -i -e "s/# $LANG UTF-8/$LANG UTF-8/" /etc/locale.gen
sudo dpkg-reconfigure --frontend=noninteractive locales
sudo update-locale LANG="$LANG"


cd "$CRISP_WORKDIR" || exit 1
touch .env


if [[ -z "${ASSETS_S3_BUCKET}" ]]; then
  echo "Not deploying to S3"
else
  crisp-cli assets --deploy-to-s3
fi

if [[ -z "${MAXMIND_LICENSE}" || -z "${MAXMIND_ACCOUNT_ID}" || -z "${MAXMIND_EDITION_IDS}" ]]; then
  echo "No Maxmind credentials found, not updating geoip"
else
  echo "Updating GeoIP Database..."
  echo -e "# Generated By CrispCMS" > /etc/GeoIP.conf
  echo -e "AccountID $MAXMIND_ACCOUNT_ID\n" >> /etc/GeoIP.conf
  echo -e "LicenseKey $MAXMIND_LICENSE\n" >> /etc/GeoIP.conf
  echo -e "EditionIDs $MAXMIND_EDITION_IDS\n" >> /etc/GeoIP.conf
  sudo geoipupdate
fi

echo "Setting System Timezone..."
sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
sudo echo $TZ > /etc/timezone
echo "Setting PHP Timezone..."
sudo printf "[Date]\ndate.timezone = \"$TZ\"\n" > /usr/local/etc/php/conf.d/timezone.ini

crisp-cli crisp --migrate
crisp-cli theme --uninstall
crisp-cli theme --install
crisp-cli theme --clear-cache
crisp-cli theme --migrate
crisp-cli theme --boot

cd / || exit 1

php-fpm -F -R -D || exit 1
crisp-cli crisp -p

sudo nginx -c /etc/nginx/nginx.conf -g "daemon off;"
